const RAW_UNITS = [
  [1, "Our new school", "新学校", "🏫", `classroom|教室|🏫;rubber|橡皮|🧽;pencil|铅笔|✏️;teacher|老师|👩‍🏫;bag|书包|🎒;crayon|蜡笔|🖍️;desk|书桌|🪑;chair|椅子|💺;book|书|📘;pen|钢笔|🖊️;pencil case|铅笔盒|👝;board|白板|⬜;door|门|🚪;window|窗户|🪟;wall|墙|🧱;playground|操场|🛝;bookcase|书架|🗄️;paper|纸|📄;ruler|尺子|📏;cupboard|橱柜|🗃️;barn|畜棚|🏚️;quiet|安静的|🤫;help|帮助|🤝;listen|倾听|👂;share|分享|🫶;floor|地板|🟫;late|迟到的|⏰;rule|规则|📏;in|在……里面|📥;on|在……上面|⬆️;under|在……下面|⬇️;next to|紧挨着|↔️;work together|一起合作|🤝`],
  [2, "All about us", "我们", "👨‍👩‍👧", `family|家庭|👨‍👩‍👧;grandfather|爷爷/外公|👴;grandpa|爷爷/外公|👴;grandmother|奶奶/外婆|👵;grandma|奶奶/外婆|👵;father|爸爸|👨;dad|爸爸|👨;mum|妈妈|👩;mother|妈妈|👩;brother|兄弟|👦;sister|姐妹|👧;nose|鼻子|👃;head|头|🧑;arm|手臂|💪;ear|耳朵|👂;hand|手|✋;body|身体|🧍;leg|腿|🦵;foot|脚|🦶;feet|脚（复数）|🦶;hair|头发|💇;face|脸|🙂;eye|眼睛|👁️;mouth|嘴巴|👄;tail|尾巴|🐾;tongue|舌头|👅;see|看|👀;hear|听|👂;smell|闻|👃;taste|尝|😋;touch|触摸|✋;blind|失明的|🦯;guide dog|导盲犬|🦮;hide and seek|捉迷藏|🙈;hide|躲藏|🫣;always|总是|🔁;boy|男孩|👦;girl|女孩|👧;friend|朋友|🧒;move|移动|↔️;put|放|📥;close|关上|🚪;open|打开|📖;clap|拍手|👏;count|数数|🔢`],
  [3, "Fun on the farm", "快乐农场", "🐮", `cow|奶牛|🐮;donkey|驴|🫏;horse|马|🐴;spider|蜘蛛|🕷️;sheep|绵羊|🐑;goat|山羊|🐐;cat|猫|🐱;chicken|鸡|🐔;dog|狗|🐶;duck|鸭子|🦆;big|大的|🐘;new|新的|✨;nice|好的|😊;old|旧的/老的|🕰️;small|小的|🐭;young|年轻的|🌱;funny|有趣的|🤪;brown|棕色的|🟤;long|长的|📏;sad|伤心的|😢;black|黑色的|⚫;happy|开心的|😄;beautiful|漂亮的|🌸;different|不同的|🌈;ugly|丑的|😖;pink|粉色的|🩷;short|短的|📐;angry|生气的|😠;ear|耳朵|👂;bee|蜜蜂|🐝;wool|羊毛|🧶;milk|牛奶|🥛;honey|蜂蜜|🍯;egg|鸡蛋|🥚;crisps|薯片|🍟;hat|帽子|🎩;colour|颜色|🎨;clothes|衣服|👕;farm|农场|🚜;mud|泥巴|🟤;white|白色的|⚪;green|绿色的|🟢;follow|跟随|👣;jump|跳|🦘`],
  [4, "Food with friends", "和朋友吃美食", "🍰", `cake|蛋糕|🍰;chocolate|巧克力|🍫;chicken|鸡肉|🍗;burger|汉堡|🍔;bread|面包|🍞;lemonade|柠檬水|🍋;water|水|💧;banana|香蕉|🍌;mango|芒果|🥭;salad|沙拉|🥗;fruit|水果|🍎;apple|苹果|🍎;grape|葡萄|🍇;orange|橙子|🍊;juice|果汁|🧃;meat|肉|🥩;meatball|肉丸|🧆;bean|豆子|🫘;sausage|香肠|🌭;ice cream|冰淇淋|🍦;ingredient|原料|🧺;pasta|意大利面|🍝;onion|洋葱|🧅;potato|土豆|🥔;rice|米饭|🍚;cheese|奶酪|🧀;carrot|胡萝卜|🥕;tomato|西红柿|🍅;dish|菜肴|🍽️;lunch|午饭|🍱;afternoon|下午|🌤️;recipe|食谱|📖;mix|搅拌|🥣;fold|折叠|🥞;add|添加|➕;cook|烹饪|👩‍🍳;cut|切|🔪;boil|煮沸|♨️;picnic|野餐|🧺;woods|树林|🌲;watermelon|西瓜|🍉;scarecrow|稻草人|🌾;crumbs|面包屑|🍞;like|喜欢|💖;please|请|🙏;thank you|谢谢|💐;omelette|煎蛋卷|🍳;Italy|意大利|🇮🇹;sandwich|三明治|🥪`],
  [5, "Happy birthday", "生日快乐", "🎁", `plane|飞机|✈️;kite|风筝|🪁;doll|玩偶|🪆;robot|机器人|🤖;ball|球|⚽;house|房子|🏠;car|汽车|🚗;bike|自行车|🚲;ship|船|🚢;mouse|老鼠|🐭;computer|电脑|💻;balloon|气球|🎈;keyboard|键盘|⌨️;board game|桌游|🎲;helicopter|直升机|🚁;teddy|泰迪熊|🧸;radio|收音机|📻;box|盒子|📦;circle|圆形|⭕;square|正方形|🟪;triangle|三角形|🔺;rectangle|长方形|▭;button|纽扣|🔘;wheel|轮子|🛞;colour|颜色|🎨;favourite|最喜欢的|💖;toy|玩具|🧸;birthday|生日|🎂;present|礼物|🎁;cool|酷的|😎;grey|灰色的|⚪;twins|双胞胎|👯;monster|怪兽|👾;alien|外星人|👽;sorry|对不起|🙏;red|红色的|🔴;orange|橙色的|🟠;yellow|黄色的|🟡;big|大的|🐘;small|小的|🐭;want|想要|💭;whose|谁的|❓;his|他的|👦;her|她的|👧;their|他们的|👥`],
  [6, "A day out", "出游日", "🚌", `tree|树|🌳;train|火车|🚆;bus stop|公交车站|🚏;garden|花园|🌷;bus|公交车|🚌;motorbike|摩托车|🏍️;car|汽车|🚗;lorry|货车|🚛;park|公园|🌳;flower|花|🌸;zoo|动物园|🦁;hippo|河马|🦛;giraffe|长颈鹿|🦒;polar bear|北极熊|🐻‍❄️;bear|熊|🐻;crocodile|鳄鱼|🐊;elephant|大象|🐘;zebra|斑马|🦓;lizard|蜥蜴|🦎;monkey|猴子|🐒;snake|蛇|🐍;tiger|老虎|🐯;Antarctica|南极洲|🧊;sea|大海|🌊;jungle|丛林|🌴;rhino|犀牛|🦏;frog|青蛙|🐸;penguin|企鹅|🐧;boa|蟒蛇|🐍;whale|鲸鱼|🐋;jellyfish|水母|🪼;grassland|草原|🌾;wild|野生的|🦁;domestic|家养的|🏠;chameleon|变色龙|🦎;ocean|海洋|🌊;shop|商店|🏪;animal|动物|🐾;town|城镇|🏘️;near|在附近|📍;cold|冷的|🥶;climb|攀爬|🧗;pool|水池|🏊;bamboo|竹子|🎋;there is|有（单数）|➕;there are|有（复数）|➕;let's|让我们|🙌;stand|站立|🧍;together|一起|🤝;hot|热的|🥵`],
  [7, "Let's play", "一起玩", "⚽", `tennis|网球|🎾;football|足球|⚽;bike|自行车|🚲;guitar|吉他|🎸;piano|钢琴|🎹;swim|游泳|🏊;basketball|篮球|🏀;television|电视|📺;horse|马|🐴;barn|谷仓|🏚️;throw|扔|🤾;catch|接住|🤲;badminton|羽毛球|🏸;skateboard|滑板|🛹;hockey|曲棍球|🏒;hit|击打|🏏;run|跑步|🏃;kick|踢|🦵;arm|手臂|💪;leg|腿|🦵;body|身体|🧍;bone|骨头|🦴;muscle|肌肉|💪;sun cream|防晒霜|🧴;water|水|💧;outside|户外|🌞;park|公园|🌳;morning|早上|🌅;Community Centre|社区中心|🏢;watch|观看|👀;ride|骑|🏇;sing|唱歌|🎤;eat|吃|🍽️;clean|清理|🧹;paint|涂画|🎨;play|玩|🕹️;stretch|伸展|🤸;jump|跳|🦘;exercise|锻炼|🏋️;important|重要的|❗;hill|小山|⛰️;ground|地面|🟫;garden|花园|🌷;fast|快地|⚡;around|在周围|🔄`],
  [8, "At home", "在家", "🏠", `bed|床|🛏️;radio|收音机|📻;bath|浴缸|🛁;mirror|镜子|🪞;bedroom|卧室|🛏️;bathroom|浴室|🚿;kitchen|厨房|🍳;dining room|餐厅|🍽️;armchair|扶手椅|🪑;living room|客厅|🛋️;sofa|沙发|🛋️;window|窗户|🪟;lamp|台灯|💡;painting|画|🖼️;phone|电话|☎️;hall|大厅|🚪;wall|墙|🧱;floor|地板|🟫;door|门|🚪;rug|地毯|🧶;clock|钟|🕰️;hut|小屋|🛖;stilt-house|高脚屋|🏠;detached house|独立住宅|🏡;ranch|大牧场|🐎;houseboat|船屋|🛥️;flat|公寓|🏢;village|村庄|🏘️;evening|晚上|🌙;home|家|🏠;can|能/会|💫;sing|唱歌|🎤;between|在……之间|↔️;behind|在……后面|🔙;in front of|在……前面|➡️;unusual|不同寻常的|✨;night|夜晚|🌃;mat|垫子|🧶;bounce|弹跳|🏀;drive|开车|🚗;pick up|捡起|🤲;point to|指向|👉;look|看|👀;know|知道|💡`],
  [9, "Happy holidays", "快乐假期", "🏖️", `hat|帽子|🧢;sunglasses|太阳镜|🕶️;shirt|衬衫|👔;shorts|短裤|🩳;jeans|牛仔裤|👖;boots|靴子|🥾;trousers|长裤|👖;dress|连衣裙|👗;baseball cap|棒球帽|🧢;T-shirt|T恤|👕;skirt|短裙|🩷;jacket|夹克|🧥;shoes|鞋子|👟;fishing|钓鱼|🎣;jellyfish|水母|🪼;sun|太阳|☀️;sea|大海|🌊;shell|贝壳|🐚;camera|相机|📷;sand|沙子|🏖️;boat|小船|⛵;fish|鱼|🐟;snow|雪|❄️;mountain|山|⛰️;forest|森林|🌲;waterfall|瀑布|💦;volcano|火山|🌋;rock|岩石|🪨;lizard|蜥蜴|🦎;hotel|旅馆|🏨;island|岛屿|🏝️;beach|海滩|🏖️;shark|鲨鱼|🦈;coconut tree|椰子树|🌴;holiday|假期|🌴;shopping|购物|🛍️;table|桌子|🪑;clothes|衣服|👕;sock|袜子|🧦;clean|清理|🧹;fly|飞|🕊️;enjoy|喜欢/享受|😊;interesting|有趣的|🤩;Africa|非洲|🌍;coconut|椰子|🥥;every day|每天|📅;invite|邀请|💌;problem|问题|❓;back|背部|🔙;heart|心脏|❤️;wait|等待|⏳;ill|生病的|🤒;come|来|🚶;put|放|📥;look|看|👀;take photos|拍照|📸;monkey|猴子|🐒;swim away|游走|🏊`]
];

const UNITS = RAW_UNITS.map(([id, title, zhTitle, icon, words]) => ({ id, title, zhTitle, icon, words: words.split(";").map((line) => { const [en, zh, emoji] = line.split("|"); return { en, zh, emoji, unit: id, key: en.toLowerCase() }; }) }));
const WORDS = UNITS.flatMap((unit) => unit.words);
const REVIEW_DAYS = [0, 1, 2, 4, 7, 15, 30];
const DAY = 86_400_000;
const PRAISE = ["Fantastic!", "Excellent!", "Terrific!", "Amazing!", "Wonderful!", "Superstar!"];
const STICKERS = [
  ["Mooncake Magic", "#ffadd0", "#8d5dbd", "🌙"], ["Rainbow Reader", "#a8e6ee", "#557ad1", "🌈"], ["Starry Library", "#bba8ef", "#754db6", "📚"],
  ["Candy Cloud", "#ffc9a8", "#dd6c9e", "🍬"], ["Ocean Sparkle", "#a7d9fb", "#3f8fc5", "🫧"], ["Garden Wish", "#b8edc8", "#4aaf8d", "🌷"]
];
const storageKey = "lumi-word-quest-v2";
const initialState = { mode: "home", unit: 1, cardTarget: null, matchTarget: null, spellTarget: null, spellSlots: [], feedback: "", stars: 0, streak: 0, spellWins: 0, celebrate: false, recognition: {}, spelling: {}, session: "unit" };
let state = loadState();
let audioContext;

function loadState() {
  try {
    const saved = JSON.parse(localStorage.getItem(storageKey)) || {};
    const previous = JSON.parse(localStorage.getItem("lumi-word-quest-v1")) || {};
    const migrated = Object.fromEntries(Object.entries(previous.progress || {}).map(([key, value]) => [key, { stage: Math.min(Number(value) || 0, 2), due: 0 }]));
    return { ...initialState, ...saved, stars: saved.stars ?? previous.stars ?? 0, streak: saved.streak ?? previous.streak ?? 0, spellWins: saved.spellWins ?? previous.spellWins ?? 0, recognition: saved.recognition || migrated, spelling: saved.spelling || {} };
  } catch { return { ...initialState }; }
}
function saveState() { localStorage.setItem(storageKey, JSON.stringify({ unit: state.unit, stars: state.stars, streak: state.streak, spellWins: state.spellWins, recognition: state.recognition, spelling: state.spelling })); }
function shuffle(items) { return [...items].sort(() => Math.random() - 0.5); }
function randomItem(items) { return items[Math.floor(Math.random() * items.length)]; }
function uniqueWords(items) { return items.filter((word, index, array) => array.findIndex((other) => other.key === word.key) === index); }
function currentUnit() { return UNITS.find((unit) => unit.id === state.unit); }
function reviewRecord(word, kind) { return state[kind][word.key]; }
function dueWords(kind) { const now = Date.now(); return uniqueWords(WORDS).filter((word) => { const record = reviewRecord(word, kind); return record && record.due <= now; }); }
function learnedCount(unit) { return uniqueWords(unit.words).filter((word) => (state.recognition[word.key]?.stage || 0) >= 3 && (state.spelling[word.key]?.stage || 0) >= 2).length; }
function dueCount() { return new Set([...dueWords("recognition"), ...dueWords("spelling")].map((word) => word.key)).size; }
function trainingPool(kind) {
  const reviewKind = kind === "cards" || kind === "match" ? "recognition" : "spelling";
  if (state.session === "review") return dueWords(reviewKind);
  return currentUnit().words;
}
function markCorrect(word, kind) {
  const bucket = state[kind];
  const before = bucket[word.key] || { stage: 0, due: 0 };
  const stage = Math.min(before.stage + 1, REVIEW_DAYS.length - 1);
  bucket[word.key] = { stage, due: Date.now() + REVIEW_DAYS[stage] * DAY };
  state.stars += 1;
  state.streak += 1;
  saveState();
}
function speak(text, options = {}) {
  if (!("speechSynthesis" in window)) return;
  window.speechSynthesis.cancel();
  const utterance = new SpeechSynthesisUtterance(text);
  utterance.lang = "en-US";
  utterance.rate = options.rate || 0.8;
  utterance.pitch = options.pitch || 1.12;
  window.speechSynthesis.speak(utterance);
}
function playSparkle() {
  const Audio = window.AudioContext || window.webkitAudioContext;
  if (!Audio) return;
  audioContext ||= new Audio();
  if (audioContext.state === "suspended") audioContext.resume();
  const start = audioContext.currentTime;
  [659.25, 783.99, 1046.5].forEach((frequency, index) => {
    const oscillator = audioContext.createOscillator(); const gain = audioContext.createGain();
    oscillator.type = "sine"; oscillator.frequency.value = frequency;
    gain.gain.setValueAtTime(0.0001, start + index * 0.075); gain.gain.exponentialRampToValueAtTime(0.12, start + index * 0.075 + 0.012); gain.gain.exponentialRampToValueAtTime(0.0001, start + index * 0.075 + 0.24);
    oscillator.connect(gain).connect(audioContext.destination); oscillator.start(start + index * 0.075); oscillator.stop(start + index * 0.075 + 0.26);
  });
}
function celebrateWithSound() { playSparkle(); speak(randomItem(PRAISE), { rate: 1.02, pitch: 1.45 }); }
function topbar() { return `<header class="topbar"><div class="brand"><span class="brand-star">✦</span><span>Lumi Word Quest</span></div><div class="status"><span>⭐ ${state.stars}</span><span>🔥 ${state.streak}</span></div></header>`; }
function nav() { const links = [["home", "魔法地图"], ["cards", "翻卡学词"], ["match", "精灵配对"], ["spell", "拼写魔法"], ["review", `循环复习${dueCount() ? ` · ${dueCount()}` : ""}`]]; return `<nav class="topnav five">${links.map(([mode, label]) => `<button class="${state.mode === mode ? "active" : ""}" onclick="setMode('${mode}')">${label}</button>`).join("")}</nav>`; }
function unitMap() { return `<section class="unit-map">${UNITS.map((unit) => { const total = uniqueWords(unit.words).length; const mastered = learnedCount(unit); return `<button class="unit-tile ${unit.id === state.unit ? "selected" : ""}" onclick="chooseUnit(${unit.id})"><span class="unit-icon">${unit.icon}</span><b>U${unit.id}</b><small>${unit.zhTitle}</small><i>${mastered}/${total}</i></button>`; }).join("")}</section>`; }
function stickerGallery() { const unlocked = Math.min(Math.floor(state.spellWins / 10), STICKERS.length); return `<section class="sticker-gallery"><div class="gallery-title"><span>✨ Lumi 贴纸收藏</span><b>${unlocked}/${STICKERS.length}</b></div><div class="sticker-row">${STICKERS.map(([name, light, dark, mark], index) => `<div class="collection-sticker ${index < unlocked ? "unlocked" : "locked"}" style="--sticker-light:${light};--sticker-dark:${dark}"><span>${mark}</span><img src="assets/lumi-mascot.png" alt="${index < unlocked ? name : "未解锁贴纸"}" /><b>${index < unlocked ? name : "???"}</b><small>${index < unlocked ? "已收藏" : `再拼 ${Math.max(0, (index + 1) * 10 - state.spellWins)} 次`}</small></div>`).join("")}</div></section>`; }
function home() { const unit = currentUnit(); const total = uniqueWords(unit.words).length; const mastered = learnedCount(unit); const percent = Math.round(mastered / total * 100); return `<section class="panel home-grid"><div><p class="eyebrow">POWER UP 1 · UNIT 1–9</p><h1>和 <span>Lumi</span><br>点亮单词魔法！</h1><p class="lead">选择一张地图学习新词；系统会把答对过的认读和拼写，按遗忘规律安排复习。</p><div class="cta-row"><button class="action-button" onclick="setMode('cards')">开始翻卡 ✨</button><button class="action-button secondary" onclick="setMode('spell')">拼写魔法 ⌨️</button>${dueCount() ? `<button class="action-button mint" onclick="setMode('review')">今日复习 ${dueCount()} 词</button>` : ""}</div><div class="progress-card"><div class="progress-orb">U${unit.id}</div><div><strong>${unit.zhTitle}：${mastered} / ${total}</strong><small>认读与拼写都通过后，单词才会点亮。</small><div class="meter"><i style="width:${percent}%"></i></div></div></div></div><div class="mascot-wrap"><img class="mascot" src="assets/lumi-mascot.png" alt="原创魔法小精灵 Lumi" /></div></section>${unitMap()}${stickerGallery()}<p class="mini-note">复习间隔：1、2、4、7、15、30 天；每正确拼写 10 次，解锁一张新贴纸。</p>`; }
function header(title, subtitle) { const unit = currentUnit(); return `<section class="panel"><div class="section-heading"><div><p class="eyebrow">${state.session === "review" ? "LUMI REVIEW LOOP" : `UNIT ${unit.id} · ${unit.title.toUpperCase()}`}</p><h2>${title}</h2><p>${subtitle}</p></div><button class="back-button" onclick="setMode('home')">← 回地图</button></div>`; }
function noWords(kind) { return `${header("今天的复习完成了！", "Lumi 已经把下一次复习安排好。")}<div class="empty-state"><img src="assets/lumi-mascot.png" alt="Lumi" /><h3>太棒了，先去学习新单词吧！</h3><button class="action-button" onclick="startUnitFromReview('${kind}')">回到 U${state.unit} 学习</button></div></section>`; }
function newCard() { state.cardTarget = randomItem(trainingPool("cards")); state.feedback = ""; }
function cards() { if (!trainingPool("cards").length) return noWords("cards"); if (!state.cardTarget || !trainingPool("cards").some((word) => word.key === state.cardTarget.key)) newCard(); const word = state.cardTarget; return `${header("翻卡学词", state.session === "review" ? "这是今天到期的认读复习词。" : "听一听、读一读，再给 Lumi 一颗星星。")}<div class="card-stage"><button class="word-card" onclick="toggleTranslation()" aria-label="翻开单词卡"><div class="word-emoji">${word.emoji}</div><h3>${word.en}</h3><p class="translation">${state.showTranslation ? word.zh : "点一下卡片看中文"}</p></button><aside class="how-to"><h3>小小魔法步骤</h3><ol><li>点 <b>🔊 听发音</b>。</li><li>点单词卡，看看中文。</li><li>会读了就点“我会啦”。</li></ol><div class="action-row"><button class="action-button secondary" onclick="speak('${word.en}')">🔊 听发音</button><button class="action-button mint" onclick="cardKnown()">我会啦 ⭐</button></div></aside></div><p class="feedback">${state.feedback}</p></section>`; }
function newMatch() { state.matchTarget = randomItem(trainingPool("match")); state.feedback = ""; }
function match() { if (!trainingPool("match").length) return noWords("match"); if (!state.matchTarget || !trainingPool("match").some((word) => word.key === state.matchTarget.key)) newMatch(); const target = state.matchTarget; const options = uniqueWords([target, ...shuffle(WORDS.filter((word) => word.key !== target.key)).slice(0, 8)]).slice(0, 4); return `${header("精灵配对", state.session === "review" ? "选出今天要复习单词的中文意思。" : "选出正确中文，让魔法光点连在一起。 ")}<div class="match-layout"><div class="question-card"><div class="big-emoji">${target.emoji}</div><p class="eyebrow">WHAT IS IT?</p><h3>${target.en}</h3><div class="action-row" style="justify-content:center"><button class="action-button secondary" onclick="speak('${target.en}')">🔊 听一听</button></div></div><div class="tip-bubble"><img class="mini-mascot" src="assets/lumi-mascot.png" alt="Lumi" /><p>请选择 <b>${target.en}</b> 的中文意思：</p><div class="choices">${shuffle(options).map((word) => `<button class="choice" onclick="chooseMatch('${word.key}', this)">${word.zh}</button>`).join("")}</div></div></div><p class="feedback ${state.feedback.includes("答对") ? "success" : state.feedback ? "error" : ""}">${state.feedback}</p></section>`; }
function newSpell() { const target = randomItem(trainingPool("spell")); const indexes = [...target.en].map((letter, index) => letter === " " || letter === "-" ? null : index).filter((index) => index !== null); const blanks = target.en.replace(/[ -]/g, "").length >= 5 ? 2 : 1; state.spellTarget = target; state.spellSlots = shuffle(indexes).slice(0, blanks).sort((a, b) => a - b); state.feedback = ""; state.celebrate = false; }
function spellGame() { if (!trainingPool("spell").length) return noWords("spell"); if (!state.spellTarget || !trainingPool("spell").some((word) => word.key === state.spellTarget.key)) newSpell(); const word = state.spellTarget; const letters = [...word.en].map((letter, index) => state.spellSlots.includes(index) ? `<input class="letter-input" inputmode="text" autocomplete="off" autocapitalize="none" spellcheck="false" aria-label="请填写第 ${index + 1} 个字母" data-index="${index}" maxlength="1" />` : `<span class="shown-letter">${letter === " " ? "&nbsp;" : letter}</span>`).join(""); const nextSticker = Math.min(Math.floor(state.spellWins / 10), STICKERS.length - 1); const [name, light, dark, mark] = STICKERS[nextSticker]; const remaining = 10 - (state.spellWins % 10); const celebration = state.celebrate ? `<div class="spell-celebration"><div class="sparkles">✦ ✧ ✦</div><img src="assets/lumi-mascot.png" alt="Lumi 庆祝" /><strong>Spell sparkle!</strong><span>拼写正确！</span></div>` : ""; return `${header("拼写魔法", state.session === "review" ? "补上到期单词的 1–2 个字母。" : "补上空缺的 1–2 个字母，练会单词拼写。")}<div class="spell-layout"><div class="spell-card"><div class="word-emoji">${word.emoji}</div><p class="eyebrow">FILL IN THE MISSING LETTERS</p><div class="spelling-word">${letters}</div><div class="action-row" style="justify-content:center"><button class="action-button secondary" onclick="speak('${word.en}')">🔊 听发音</button><button class="action-button mint" onclick="checkSpelling()">施放拼写魔法 ✨</button></div><p class="feedback ${state.feedback.includes("正确") ? "success" : state.feedback ? "error" : ""}">${state.feedback}</p></div><aside class="spell-side"><img class="spell-mascot" src="assets/lumi-mascot.png" alt="Lumi" /><div class="next-sticker" style="--sticker-light:${light};--sticker-dark:${dark}"><span>${mark}</span><img src="assets/lumi-mascot.png" alt="下一张贴纸" /><b>${name}</b><small>再正确拼写 ${remaining} 次解锁</small></div></aside></div>${celebration}</section>`; }
function review() { const recognition = dueWords("recognition").length; const spelling = dueWords("spelling").length; return `${header("Lumi 循环复习", "系统依据艾宾浩斯遗忘曲线，只安排该复习的单词。")}<div class="review-grid"><div class="review-card"><span>👀</span><h3>认读复习</h3><b>${recognition} 个词</b><p>翻卡和配对，巩固“看见就认识”。</p><button class="action-button ${recognition ? "" : "disabled"}" ${recognition ? "onclick=\"startReview('recognition')\"" : "disabled"}>开始认读</button></div><div class="review-card"><span>⌨️</span><h3>拼写复习</h3><b>${spelling} 个词</b><p>补全字母，巩固“听到就会拼”。</p><button class="action-button secondary ${spelling ? "" : "disabled"}" ${spelling ? "onclick=\"startReview('spelling')\"" : "disabled"}>开始拼写</button></div></div><div class="ebbinghaus"><b>复习节奏</b><span>今天学会</span><i>→</i><span>1 天</span><i>→</i><span>2 天</span><i>→</i><span>4 天</span><i>→</i><span>7 天</span><i>→</i><span>15 天</span><i>→</i><span>30 天</span></div></section>`; }
function render() { const views = { home, cards, match, spell: spellGame, review }; document.getElementById("app").innerHTML = `<div class="app-shell">${topbar()}${nav()}${views[state.mode]()}</div>`; }
function chooseUnit(id) { state.unit = id; state.session = "unit"; state.cardTarget = state.matchTarget = state.spellTarget = null; render(); }
function setMode(mode) { state.mode = mode; state.feedback = ""; if (mode !== "review" && mode !== "home") state.session = state.session || "unit"; if (mode === "cards") newCard(); if (mode === "match") newMatch(); if (mode === "spell") newSpell(); render(); }
function startReview(kind) { state.session = "review"; state.mode = kind === "recognition" ? "cards" : "spell"; state.cardTarget = state.matchTarget = state.spellTarget = null; if (state.mode === "cards") newCard(); else newSpell(); render(); }
function startUnitFromReview(kind) { state.session = "unit"; state.mode = kind; if (kind === "cards") newCard(); else newSpell(); render(); }
function toggleTranslation() { state.showTranslation = !state.showTranslation; render(); }
function cardKnown() { markCorrect(state.cardTarget, "recognition"); state.feedback = `太棒了！${state.cardTarget.en} 的认读复习已安排。`; state.showTranslation = false; setTimeout(() => { state.cardTarget = null; render(); }, 650); render(); }
function chooseMatch(key, button) { const correct = key === state.matchTarget.key; button.classList.add(correct ? "correct" : "wrong"); if (correct) { markCorrect(state.matchTarget, "recognition"); celebrateWithSound(); state.feedback = `答对了！${state.matchTarget.en} = ${state.matchTarget.zh} ⭐`; setTimeout(() => { state.matchTarget = null; render(); }, 700); } else { state.streak = 0; saveState(); state.feedback = "再想一想，听一听单词提示吧。"; } }
function checkSpelling() { const inputs = [...document.querySelectorAll(".letter-input")]; const values = new Map(inputs.map((input) => [Number(input.dataset.index), input.value.trim().toLowerCase()])); const correct = state.spellSlots.every((index) => values.get(index) === state.spellTarget.en[index].toLowerCase()); if (correct) { markCorrect(state.spellTarget, "spelling"); state.spellWins += 1; celebrateWithSound(); state.feedback = `正确！${state.spellTarget.en} 的拼写复习已安排。`; state.celebrate = true; saveState(); render(); setTimeout(() => { state.spellTarget = null; state.celebrate = false; render(); }, 1350); } else { state.streak = 0; state.feedback = "还差一点点，再听一次发音、看看空格吧。"; saveState(); render(); } }
window.setMode = setMode; window.chooseUnit = chooseUnit; window.toggleTranslation = toggleTranslation; window.cardKnown = cardKnown; window.speak = speak; window.chooseMatch = chooseMatch; window.checkSpelling = checkSpelling; window.startReview = startReview; window.startUnitFromReview = startUnitFromReview;
if ("serviceWorker" in navigator) navigator.serviceWorker.register("sw.js").catch(() => {});
render();
